import { HistoricalEvent } from "@/types/historical";

export const historicalEvents: HistoricalEvent[] = [
  {
    id: "independence-1960",
    year: 1960,
    month: 10,
    day: 1,
    title: "Nigeria Gains Independence",
    description:
      "Nigeria became an independent nation from British colonial rule.",
    detailedStory:
      "On October 1, 1960, Nigeria gained independence from Britain. Prime Minister Abubakar Tafawa Balewa declared Nigeria as a sovereign nation. The green-white-green flag was hoisted for the first time at the Race Course in Lagos amidst great celebration.",
    images: ["/images/independence-1960.jpg"],
    category: "politics",
    significance: "high",
    region: ["national"],
    peopleInvolved: [
      "Abubakar Tafawa Balewa",
      "Nnamdi Azikiwe",
      "Obafemi Awolowo",
      "Sir James Robertson",
    ],
  },
  {
    id: "republic-1963",
    year: 1963,
    month: 10,
    day: 1,
    title: "Nigeria Becomes a Republic",
    description:
      "Nigeria transitioned to a republic with Nnamdi Azikiwe as first president.",
    detailedStory:
      "Nigeria became a republic within the Commonwealth, with Nnamdi Azikiwe as the first indigenous head of state. This marked the final step in complete sovereignty from British rule.",
    images: ["/images/republic-1963.jpg"],
    category: "politics",
    significance: "high",
    region: ["national"],
    peopleInvolved: ["Nnamdi Azikiwe", "Abubakar Tafawa Balewa"],
  },
  {
    id: "first-coup-1966",
    year: 1966,
    month: 1,
    day: 15,
    title: "First Military Coup",
    description: "First military coup led by Major Chukwuma Kaduna Nzeogwu.",
    detailedStory:
      "The first military coup in Nigeria's history resulted in the deaths of Prime Minister Abubakar Tafawa Balewa and several regional premiers. This event marked the beginning of military intervention in Nigerian politics.",
    images: ["/images/coup-1966.jpg"],
    category: "politics",
    significance: "high",
    region: ["national"],
    peopleInvolved: ["Chukwuma Nzeogwu", "Johnson Aguiyi-Ironsi"],
  },
  {
    id: "civil-war-1967",
    year: 1967,
    month: 7,
    day: 6,
    title: "Nigerian Civil War Begins",
    description: "The Biafran War started, lasting until 1970.",
    detailedStory:
      "The Nigerian Civil War, also known as the Biafran War, was fought between the federal government and the secessionist state of Biafra. The conflict resulted from ethnic tensions and resulted in significant humanitarian crisis.",
    images: ["/images/civil-war-1967.jpg"],
    category: "politics",
    significance: "high",
    region: ["east"],
    peopleInvolved: ["Yakubu Gowon", "Chukwuemeka Ojukwu", "Odumegwu Ojukwu"],
  },
  {
    id: "war-ends-1970",
    year: 1970,
    month: 1,
    day: 15,
    title: "Civil War Ends",
    description: "Biafra surrendered, ending the Nigerian Civil War.",
    detailedStory:
      "The war ended with the surrender of Biafran forces. The famous 'No victor, no vanquished' policy was declared to promote national reconciliation and rebuilding.",
    images: ["/images/war-ends-1970.jpg"],
    category: "politics",
    significance: "high",
    region: ["east", "national"],
    peopleInvolved: ["Yakubu Gowon", "Philip Effiong"],
  },
  {
    id: "oil-boom-1970s",
    year: 1971,
    title: "Oil Boom Era Begins",
    description:
      "Nigeria joined OPEC and experienced economic transformation through oil.",
    detailedStory:
      "Nigeria's membership in OPEC and rising oil prices transformed the economy. This period saw massive infrastructure development but also increased corruption and dependency on oil.",
    images: ["/images/oil-boom-1970s.jpg"],
    category: "innovation",
    significance: "high",
    region: ["national"],
    peopleInvolved: ["Yakubu Gowon", "Shehu Shagari"],
  },
  {
    id: "festac-1977",
    year: 1977,
    month: 1,
    title: "FESTAC 77",
    description:
      "Second World Black and African Festival of Arts and Culture held in Lagos.",
    detailedStory:
      "FESTAC 77 was a major international festival celebrating African culture and arts, attracting participants from across Africa and the diaspora. It showcased Nigeria's cultural richness on the global stage.",
    images: ["/images/festac-77.jpg"],
    category: "culture",
    significance: "high",
    region: ["lagos"],
    peopleInvolved: ["Olusegun Obasanjo", "Fela Kuti"],
  },
  {
    id: "afcon-1980",
    year: 1980,
    month: 3,
    day: 22,
    title: "Nigeria Hosts and Wins AFCON",
    description:
      "Super Eagles won their first Africa Cup of Nations on home soil.",
    detailedStory:
      "Nigeria hosted and won the African Cup of Nations for the first time, defeating Algeria 3-0 in the final. This victory united the nation and marked Nigeria's arrival as a football power.",
    images: ["/images/afcon-1980.jpg"],
    category: "sports",
    significance: "high",
    region: ["national"],
    peopleInvolved: ["Christian Chukwu", "Segun Odegbami", "Best Ogedegbe"],
  },
  {
    id: "maradona-1989",
    year: 1989,
    title: "U-20 World Cup Victory",
    description: "Nigeria won FIFA U-20 World Cup, defeating the Soviet Union.",
    detailedStory:
      "The Flying Eagles, led by players like Nduka Ugbade, won Nigeria's first FIFA-organized world championship, announcing the country's emergence as a football talent factory.",
    images: ["/images/u20-1989.jpg"],
    category: "sports",
    significance: "medium",
    region: ["national"],
    peopleInvolved: ["Nduka Ugbade", "Christopher Ohen"],
  },
  {
    id: "june-12-1993",
    year: 1993,
    month: 6,
    day: 12,
    title: "June 12 Presidential Election",
    description:
      "Historic presidential election annulled by military government.",
    detailedStory:
      "Considered Nigeria's freest and fairest election, won by Moshood Abiola, but annulled by General Ibrahim Babangida. This led to political crisis and pro-democracy movements.",
    images: ["/images/june12-1993.jpg"],
    category: "politics",
    significance: "high",
    region: ["national"],
    peopleInvolved: ["Moshood Abiola", "Ibrahim Babangida", "Ernest Shonekan"],
  },
  {
    id: "olympic-gold-1996",
    year: 1996,
    month: 8,
    day: 3,
    title: "Olympic Football Gold",
    description: "Nigeria won gold in football at Atlanta Olympics.",
    detailedStory:
      "The Nigerian football team, known as the Dream Team, won Olympic gold in a thrilling final against Argentina, coming from behind to win 3-2. This was Africa's first Olympic football gold.",
    images: ["/images/olympic-1996.jpg"],
    category: "sports",
    significance: "high",
    region: ["national"],
    peopleInvolved: ["Nwankwo Kanu", "Jay-Jay Okocha", "Daniel Amokachi"],
  },
  {
    id: "democracy-1999",
    year: 1999,
    month: 5,
    day: 29,
    title: "Return to Civilian Rule",
    description:
      "Nigeria returned to democratic governance after years of military rule.",
    detailedStory:
      "Olusegun Obasanjo was elected as president, marking the end of 16 years of continuous military rule and beginning of the Fourth Republic, which continues to this day.",
    images: ["/images/democracy-1999.jpg"],
    category: "politics",
    significance: "high",
    region: ["national"],
    peopleInvolved: ["Olusegun Obasanjo", "Abdulsalami Abubakar"],
  },
  {
    id: "miss-world-2001",
    year: 2001,
    title: "Agbani Darego Wins Miss World",
    description: "First Black African to win Miss World pageant.",
    detailedStory:
      "Agbani Darego made history as the first Black African woman to win the Miss World crown, putting Nigeria on the global map of beauty and fashion.",
    images: ["/images/miss-world-2001.jpg"],
    category: "achievement",
    significance: "medium",
    region: ["national"],
    peopleInvolved: ["Agbani Darego"],
  },
  {
    id: "nollywood-boom-2000s",
    year: 2002,
    title: "Nollywood Recognition",
    description: "UNESCO declared Nollywood second largest film industry.",
    detailedStory:
      "Nollywood was recognized as the second-largest film industry in the world by volume, telling authentic African stories and creating employment for millions.",
    images: ["/images/nollywood.jpg"],
    category: "culture",
    significance: "high",
    region: ["national"],
    peopleInvolved: [
      "Geneviève Nnaji",
      "Pete Edochie",
      "Omotola Jalade-Ekeinde",
    ],
  },
  {
    id: "afcon-2013",
    year: 2013,
    title: "AFCON Victory in South Africa",
    description: "Super Eagles won third Africa Cup of Nations title.",
    detailedStory:
      "Nigeria won its third AFCON title under coach Stephen Keshi, who became the second person to win as both player and coach.",
    images: ["/images/afcon-2013.jpg"],
    category: "sports",
    significance: "high",
    region: ["national"],
    peopleInvolved: ["Stephen Keshi", "Vincent Enyeama", "John Mikel Obi"],
  },
  {
    id: "economy-2014",
    year: 2014,
    title: "Largest Economy in Africa",
    description: "Nigeria became Africa's largest economy after GDP rebasing.",
    detailedStory:
      "After recalculating its GDP to include emerging sectors like telecommunications and entertainment, Nigeria emerged as the largest economy in Africa, surpassing South Africa.",
    images: ["/images/economy-2014.jpg"],
    category: "innovation",
    significance: "high",
    region: ["national"],
    peopleInvolved: ["Ngozi Okonjo-Iweala", "Goodluck Jonathan"],
  },
  {
    id: "buhari-election-2015",
    year: 2015,
    title: "Historic Power Transition",
    description: "First opposition party victory in presidential election.",
    detailedStory:
      "Muhammadu Buhari's victory marked the first time an opposition party defeated an incumbent president through the ballot box, strengthening Nigeria's democracy.",
    images: ["/images/election-2015.jpg"],
    category: "politics",
    significance: "high",
    region: ["national"],
    peopleInvolved: ["Muhammadu Buhari", "Goodluck Jonathan"],
  },
  {
    id: "endsars-2020",
    year: 2020,
    month: 10,
    title: "End SARS Protests",
    description: "Youth-led protests against police brutality.",
    detailedStory:
      "Nigerian youth organized nationwide protests against police brutality, specifically targeting the Special Anti-Robbery Squad (SARS). The movement gained international attention and highlighted youth activism.",
    images: ["/images/endsars-2020.jpg"],
    category: "politics",
    significance: "high",
    region: ["national"],
    peopleInvolved: ["Nigerian Youth", "Falz", "Runtown"],
  },
  {
    id: "afcfta-2021",
    year: 2021,
    title: "African Continental Free Trade Area",
    description: "Nigeria ratified the AfCFTA agreement.",
    detailedStory:
      "Nigeria's ratification of the African Continental Free Trade Area agreement positioned the country as a key player in continental economic integration.",
    images: ["/images/afcfta-2021.jpg"],
    category: "innovation",
    significance: "medium",
    region: ["national"],
    peopleInvolved: ["Muhammadu Buhari", "Wamkele Mene"],
  },
  {
    id: "burna-boy-grammy-2021",
    year: 2021,
    title: "Burna Boy Wins Grammy",
    description: "First Nigerian solo artist to win Grammy Award.",
    detailedStory:
      "Burna Boy won the Best Global Music Album for 'Twice As Tall', cementing Nigeria's place in global music and the Afrobeats movement.",
    images: ["/images/grammy-2021.jpg"],
    category: "culture",
    significance: "high",
    region: ["national"],
    peopleInvolved: ["Burna Boy", "Damini Ogulu"],
  },
  {
    id: "tinubu-election-2023",
    year: 2023,
    title: "2023 General Elections",
    description: "Bola Tinubu elected president in competitive elections.",
    detailedStory:
      "The 2023 elections featured three strong candidates and significant technological innovations in the electoral process, including the Bimodal Voter Accreditation System.",
    images: ["/images/election-2023.jpg"],
    category: "politics",
    significance: "high",
    region: ["national"],
    peopleInvolved: ["Bola Tinubu", "Atiku Abubakar", "Peter Obi"],
  },
  // Additional significant events
  {
    id: "first-tv-1959",
    year: 1959,
    title: "First Television Service in Africa",
    description: "Western Nigeria Television launched, first in Africa.",
    detailedStory:
      "WNTV became the first television service in Africa, starting in Ibadan. This marked Nigeria's early leadership in media and broadcasting on the continent.",
    images: ["/images/wntv-1959.jpg"],
    category: "innovation",
    significance: "medium",
    region: ["west"],
    peopleInvolved: ["Obafemi Awolowo"],
  },
  {
    id: "national-theatre-1976",
    year: 1976,
    title: "National Theatre Commissioned",
    description: "Iconic National Theatre built for FESTAC 77.",
    detailedStory:
      "The National Theatre in Lagos was commissioned as a cultural landmark and venue for FESTAC 77, becoming an enduring symbol of Nigerian arts and culture.",
    images: ["/images/national-theatre-1976.jpg"],
    category: "culture",
    significance: "medium",
    region: ["lagos"],
    peopleInvolved: ["Olusegun Obasanjo"],
  },
  {
    id: "wole-soyinka-nobel-1986",
    year: 1986,
    title: "First African Nobel Laureate in Literature",
    description: "Wole Soyinka won Nobel Prize in Literature.",
    detailedStory:
      "Professor Wole Soyinka became the first African to win the Nobel Prize in Literature, bringing global recognition to African literature and intellectualism.",
    images: ["/images/soyinka-1986.jpg"],
    category: "achievement",
    significance: "high",
    region: ["national"],
    peopleInvolved: ["Wole Soyinka"],
  },
  {
    id: "all-africa-games-2003",
    year: 2003,
    title: "Hosted All Africa Games",
    description: "Nigeria successfully hosted the 8th All Africa Games.",
    detailedStory:
      "The games held in Abuja showcased Nigeria's organizational capabilities and featured participation from 53 African nations.",
    images: ["/images/all-africa-games-2003.jpg"],
    category: "sports",
    significance: "medium",
    region: ["abuja"],
    peopleInvolved: ["Sports Ministry"],
  },
  {
    id: "banking-reform-2004",
    year: 2004,
    title: "Banking Sector Consolidation",
    description: "Major banking reforms increased capital base requirements.",
    detailedStory:
      "The banking consolidation exercise under Professor Charles Soludo reduced the number of banks from 89 to 25, creating stronger financial institutions.",
    images: ["/images/banking-2004.jpg"],
    category: "innovation",
    significance: "medium",
    region: ["national"],
    peopleInvolved: ["Charles Soludo", "Chukwuma Soludo"],
  },
  {
    id: "under-17-worldcup-2007",
    year: 2007,
    title: "U-17 World Cup Record",
    description: "Golden Eaglets reached third consecutive final.",
    detailedStory:
      "Nigeria's U-17 team reached their third consecutive FIFA U-17 World Cup final, winning twice and establishing a world record for youth football consistency.",
    images: ["/images/u17-2007.jpg"],
    category: "sports",
    significance: "medium",
    region: ["national"],
    peopleInvolved: ["Kelechi Iheanacho", "Victor Osimhen"],
  },
  {
    id: "amcon-2010",
    year: 2010,
    title: "AMCON Establishment",
    description: "Asset Management Corporation of Nigeria created.",
    detailedStory:
      "AMCON was established to stabilize the banking system by acquiring non-performing loans, preventing systemic financial collapse.",
    images: ["/images/amcon-2010.jpg"],
    category: "innovation",
    significance: "medium",
    region: ["national"],
    peopleInvolved: ["Goodluck Jonathan", "Lamido Sanusi"],
  },
  {
    id: "chibok-girls-2014",
    year: 2014,
    month: 4,
    day: 14,
    title: "Chibok Girls Abduction",
    description: "Boko Haram kidnapped 276 schoolgirls in Chibok.",
    detailedStory:
      "The mass abduction brought global attention to terrorism in Nigeria and sparked the #BringBackOurGirls campaign.",
    images: ["/images/chibok-2014.jpg"],
    category: "politics",
    significance: "high",
    region: ["north-east"],
    peopleInvolved: ["Goodluck Jonathan", "Malala Yousafzai", "Michelle Obama"],
  },
  {
    id: "rail-modernization-2016",
    year: 2016,
    title: "Railway Modernization Begins",
    description: "Abuja-Kaduna standard gauge railway launched.",
    detailedStory:
      "The modern railway project marked the beginning of Nigeria's rail transport modernization, reducing travel time and boosting economic activities.",
    images: ["/images/railway-2016.jpg"],
    category: "innovation",
    significance: "medium",
    region: ["abuja", "kaduna"],
    peopleInvolved: ["Muhammadu Buhari", "Rotimi Amaechi"],
  },
  {
    id: "dangote-refinery-2023",
    year: 2023,
    title: "Dangote Refinery Commissioned",
    description: "World's largest single-train refinery opened.",
    detailedStory:
      "The Dangote Refinery, Africa's largest oil refinery, began operations with potential to transform Nigeria's energy sector and reduce fuel imports.",
    images: ["/images/refinery-2023.jpg"],
    category: "innovation",
    significance: "high",
    region: ["lagos"],
    peopleInvolved: ["Aliko Dangote", "Muhammadu Buhari"],
  },
];
